version: '3.8'

services:
  db:
    image: kissbe/auo_db:latest
    container_name: auo_db
    restart: always
    ports:
      - "32769:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  backend:
    image: kissbe/auo_backend:latest
    container_name: auo_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network

volumes:
  pgdata:

networks:
  backend_network:
    driver: bridge
