version: '3.8'

services:
  db:
    build: ./db
    container_name: auo_db
    restart: always
    ports:
      - "32769:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: ./
    container_name: auo_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_network


volumes:
  pgdata:

networks:
  backend_network:
    driver: bridge
